Project_2/config/routes.rb
Rails.application.routes.draw do
  
  get 'homepages/index'

  resources :user_wines , only: [:index, :show]

  resources :user_notes , only: [:index, :show]

  resources :sessions, only: [:new, :create]

  delete "/sessions" , to: "sessions#destroy"

  resources :notes

  resources :users

  resources :wines

  delete "/wines/:id" , to: "wines#destroy"

  post "/notes/:id/wine_note_new", to: "notes#wine_note_new"

  root 'homepages#index'

  
end

Project_2/app/models/bottle.rb
class Bottle < ActiveRecord::Base
	belongs_to :user
	belongs_to :wine
	has_many :notes
end

Project_2/app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :bottle
end

Project_2/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :bottles
	has_many :notes, through: :bottles
	has_many :wines, -> {distinct}, through: :bottles
	validates :email, presence: true, uniqueness: true
end

Project_2/app/models/wine.rb
class Wine < ActiveRecord::Base
	has_many :bottles
	has_many :users, through: :bottles
	has_many :notes, through: :bottles
end

Project_2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	#if I have a current_user value return that, otherwise find one
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]

  end	

  def logged_in?
  	#!! = true or false, so this function tells us whether or not we're logged in
  	!!current_user
  	
  end

  def authenticate
  	#checks if user logged in and redirects to another page
  	unless logged_in?
  		redirect_to "/sessions/new"
  	end	
  end

end

Project_2/app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def index
  end
end

Project_2/app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :set_note, only: [:show]
  def index
  	@notes = Note.all

    @title = "CellarBook notes"

  end

  def show
  	
    @wine = @note.bottle.wine

  end


  def new

    @star = '<i class="fa fa-star">'

    @note = Note.new

  end


  def create
    
    @note = Note.create(note_params)
  
  end  

  def wine_note_new

    bottles = Bottle.where(:wine_id => params[:id] , :user => current_user, :drunk => false)

    bottle = bottles.first

    bottle.drunk = true

    bottle.save

    bottle.notes.create(note_params)

    redirect_to "/user_wines/#{params[:id]}"

  end



  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:appearance, :nose, :palate, :conclusion, :rating, :created_at, :maturity)
    end
end

Project_2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	# user has sent email and password

  	# see if the user/email exists (using the email submitted in the form in new view)

  	user = User.find_by_email(params[:email])

  	# .authenticate encrypts the password sent from the form and checks the encrypted hash against the database returning true or false depending on whether it exists
  	if user && user.authenticate(params[:password])

  		#session stores data for the duration of the session: the symbol is user_id and the value is user.id
  		session[:user_id] = user.id

  		#this tells you that you have logged in successfully, not that you are already logged in
  		redirect_to user_wines_path, notice: "logged in"

  	else

  		render "new"

  	end

  end

  def destroy
  	#unset the session id (ie, log out) and redirect
  	session[:user_id] = nil
  	redirect_to "/sessions/new"
  end
end

Project_2/app/controllers/user_notes_controller.rb
class UserNotesController < ApplicationController
    before_action :set_note, only: [:show, :edit, :update, :destroy]
  def index
    @notes = current_user.notes

    @title = "Your notes"

  end

  def show

    @wine = @note.bottle.wine

    @wine_details = "#{@wine.name} #{@wine.vintage}"
    
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:appearance, :nose, :palate, :conclusion, :rating, :created_at, :maturity)
    end
end

Project_2/app/controllers/user_wines_controller.rb
class UserWinesController < ApplicationController
  before_action :set_wine, only: [:show]
  def index
    @wines = current_user.wines

    @title = "Your wines"

  end

  def show
    
    @notes = Note.joins(:bottle).where(bottles: { :user_id => current_user, :wine_id => @wine })

    @note = Note.new

    @bottles = @wine.bottles.where(:user => current_user, :drunk => false)

    @quantity = @bottles.count

    @users = @wine.users

    # binding.pry
  
  end

  def drink_wine

    

  end

  private
    def set_wine
      @wine = current_user.wines.find(params[:id])
    end

    def wine_params
      params.require(:wine).permit(:producer, :name, :vintage, :alcohol, :region, :country, :grape, :window)
    end
end

Project_2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, only: [:show]
  def index
  end

  def show

    @user = current_user
    
  end

  def new

    if logged_in?

      redirect_to root_path

    end

    @user = User.new
  
  end

  def create

    if logged_in?

      redirect_to root_path

    end

    @user = User.new(user_params)

    if @user.save

      redirect_to user_path

    else
      # shows the user the completed form again
      render "new"

    end
    
  end

  def edit

    @user = current_user
    
  end

  def update

    current_user.update(user_params)

    redirect_to user_path

  end  

  private

  def user_params

    params.require(:user).permit(:email, :password, :password_confirmation)

  end 

end

Project_2/app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]
  def index

    @wines = Wine.all

    @title = "CellarBook wines"

  end

  def show
    
    @wine_details = "#{@wine.name} #{@wine.vintage}"

    @notes = @wine.notes

    @users = @wine.users

  end

  def new

    @wine = Wine.new

  end

  def create

    if !logged_in?

      redirect_to root_path

    end

    @wine = Wine.new(wine_params)

    if @wine.save

      quantity = bottle_params[:quantity].to_i

      quantity.times do |i|

        @bottle = Bottle.create(wine: @wine , user: current_user)
            
      end

      redirect_to action: @users_wine

    else
      # shows the user the completed form again
      render "new"

    end
    
  end

  private
    def set_wine
      @wine = Wine.find(params[:id])
    end

    def wine_params
      params.require(:wine).permit(:producer, :name, :vintage, :alcohol, :region, :country, :grape, :window_start, :window_end, :style)
    end

    def bottle_params
      params.require(:bottle).permit(:vendor, :price, :quantity)
    end
end

Project_2/app/helpers/application_helper.rb
module ApplicationHelper
end

Project_2/app/helpers/homepages_helper.rb
module HomepagesHelper
end

Project_2/app/helpers/notes_helper.rb
module NotesHelper
end

Project_2/app/helpers/sessions_helper.rb
module SessionsHelper
end

Project_2/app/helpers/user_notes_helper.rb
module UserNotesHelper
end

Project_2/app/helpers/user_wines_helper.rb
module UserWinesHelper
end

Project_2/app/helpers/users_helper.rb
module UsersHelper
end

Project_2/app/helpers/wines_helper.rb
module WinesHelper
end

Project_2/app/views/homepages/index.html.erb
<div class="homepage">
    <div class="homepage-inner">
        <div class="row" id="welcome">
            <div class="small-6 columns small-offset-3 text-center">
                <%= link_to wines_path do %>
                	<h1>CellarBook</h1>
                <% end %>	
            </div>
        </div>
    </div>
</div>

Project_2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row" id="topNav">
      <div class="small-10 small-offset-1 columns">
         <div class="contain-to-grid sticky">   
          <nav class="top-bar" data-topbar role="navigation">
            <ul class="title-area">
              <li class="name">
                <h1><a href="/">CellarBook</a></h1>
              </li>
               <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
              <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
            </ul>

            <section class="top-bar-section">
              <!-- Right Nav Section -->
              <ul class="right">
                <!-- <li class="has-form">
                  <div class="row collapse">
                    <div class="large-8 small-9 columns">
                      <input type="text" placeholder="eg, wine, region, user">
                    </div>
                    <div class="large-4 small-3 columns">
                      <a href="#" class="alert button expand">Search</a>
                    </div>
                  </div>
                </li> -->
                <li>
                  <a><%= link_to 'Add wine', new_wine_path %></a>
                </li>

                <% if current_user %>
                  <ul class="right">
                    <li class="active"><%= link_to 'Log out' , sessions_path , method: :delete, data: {confirm: 'Are you sure?'} %></li>
                  </ul>
                <% else %>           
                  <ul class="left">
                    <li><a href="/sessions/new">Sign in</a></li>
                  </ul>
                  <ul class="right">
                    <li class="active"><a href="/users/new">Sign up</a></li>
                  </ul>
                <% end %>  
              </ul>

              <!-- Left Nav Section -->
              <ul class="left">
                <li><a href="/wines">Wines</a></li>
                <li><a href="/notes">Notes</a></li>
              </ul>
            </section>
          </nav>
         </div>
        </div> 
      </div>
  
      <div class="row" id="subNav">
        <div class="small-10 small-offset-1 columns">  
         <% if current_user %>

            <% if controller_name == "user_wines" %>
              
              <%= render "/partials/user_wines_subnav" %>

            <% elsif controller_name == "user_notes" %>

              <%= render "/partials/user_notes_subnav" %> 

            <% else %>

              <%= render "/partials/unmarked_subnav" %>   

            <% end %>

         <% end %>
        </div>
      </div>

      <!-- <div class="row" id="title">
        <div class="small-10 small-offset-1 columns">   
          <h5><%= @title %></h5>
        </div>
      </div> -->

      <%= yield %>
     
    </body>
   </div>
  </div>  
</html>

Project_2/app/views/notes/index.html.erb
<div class="row" id="mainBackground">
  <div class="small-10 small-offset-1 columns">
  	<h5 class="head">CellarBook notes</h5>  
    <%= render "/partials/show_notes" %>
  </div>
</div>

Project_2/app/views/notes/new.html.erb
<h5>Add note</h5>

<%= form_for(@note) do |f| %>

	    <div class="field">
	    	<%= f.label :appearance %>
	    	<%= f.text_field :appearance %>
	    </div>

	    <div class="field">
	    	<%= f.label :nose %>
	    	<%= f.text_field :nose %>
	    </div>

	    <div class="field">
	    	<%= f.label :palate %>
	    	<%= f.text_field :palate %>
	    </div>

	    <div class="field">
	    	<%= f.label :conclusion %>
	    	<%= f.text_field :conclusion %>
	    </div>

	    <div class="field">
	    	<%= f.label :maturity %>
	    	<%= f.text_field :maturity %>
	    </div>

	    <div class="field">
	    	<%= f.label :rating %>
	    	<%= f.text_field :rating %>
	    </div>

	    <div class="field">
	    	<%= label_tag 'quantity drunk' %>
	    	<%= text_field_tag 'bottle[quantity]' %>
	    </div>

	    <div class="actions">
	      <%= f.submit "Add note" %>
	    </div>

	<%= token_tag %>

<% end %>

Project_2/app/views/notes/show.html.erb
<div class="row" id="mainBackground">
  <div class="small-10 small-offset-1 columns"> 
  	<div class="mainDisplay"> 
			<div class="row" id="userWineMain">
		  	<div class="small-12 columns">
		  		<div class="backLink">
						<i class="fa fa-long-arrow-left"></i>	
						<%= link_to 'back to notes', notes_path %>
					</div>
					<%= render "/partials/show_wine" %>
					<div class="small-3 columns">				
					</div>
				</div>
			</div>		
		</div>
	</div>
</div>

<div class="row" id="notesArea">
  <div class="small-10 small-offset-1 columns">
		<%= render "/partials/show_note" %>
	</div>
</div>

Project_2/app/views/partials/_all_wines.html.erb
<div class="row">
	<div class="small-12 columns">
		<table>
			<thead>
			    <tr>
			    <th width="50">Style</th>
		      	<th width="150">Name</i> </th>
		      	<th width="100">Region</th>
		      	<th width="100">Country</th>
		      	<th width="100">Drinking window</th>
		      	<th width="50">In cellar</th>
			    </tr>
			</thead>

			<tbody>
			<% @wines.each do |wine| %>	
			<% full_name = "#{wine.producer} #{wine.name} #{wine.vintage}"	%>
			<% quantity = wine.bottles.where(:user => current_user, :drunk => false).count %>
			<% if wine.style == "sparkling" %>

				<% style_url = "/assets/champagne.jpg" %>

			<% elsif wine.style == "red" %>

				<% style_url = "/assets/red.jpg" %>
				
			<% elsif wine.style == "white" %>

				<% style_url = "/assets/white.jpg" %>
			
			<% elsif wine.style == "rose" %>

				<% style_url = "/assets/rose.jpg" %>

			<% elsif wine.style == "sweet" %>

				<% style_url = "/assets/sweet.jpg" %>				

			<% end %>
				<tr>
					<td><%= image_tag(style_url, size: "50x30") %></td>
					<td>
						<% if controller_name == "user_wines" %>
							
							<%= link_to full_name, user_wine_path(wine) %>

						<% elsif controller_name == "wines" %>

							<%= link_to full_name, wine %>

						<% end %>
					</td>
					<td><%= wine.region %></td>
					<td><%= wine.country %></td>
					<td class="window"><%= "#{wine.window_start}–#{wine.window_end}" %></td>
					<td class="quantity"><%= quantity %></td>
				</tr>
			<% end %>		
			</tbody>
		</table>
	</div>
</div>	

Project_2/app/views/partials/_backlink.html.erb
<div class="backLink">
	<i class="fa fa-long-arrow-left"></i>	
	<%= link_to 'back to wines', user_wines_path %>
</div>

Project_2/app/views/partials/_drink_wine.html.erb
<h5>Drink wine</h5>

<%= form_for :bottles, :url => {action: 'drink_wine', controller: 'user_wines'}  do |f| %>

	    <div class="field">
	    	<%= f.label :quantity %>
	    	<%= f.number_field :quantity %>
	    </div>

	<%= token_tag %>

<% end %>

Project_2/app/views/partials/_new_note_form.html.erb
<div class="row" id="">
  	<div class="small-12 columns">
			<div id="">
			

<%= form_for :note, :url => {action: 'wine_note_new', controller: 'notes'} do |f| %>
		<div class="userForm">
			<h5>Add note</h5>
		    <div class="field" id="textInput">
		    	<%= f.label :appearance %>
		    	<%= f.text_area :appearance %>
		    </div>

		    <div class="field" id="textInput">
		    	<%= f.label :nose %>
		    	<%= f.text_area :nose %>
		    </div>

		    <div class="field" id="textInput">
		    	<%= f.label :palate %>
		    	<%= f.text_area :palate %>
		    </div>
	    
		    <div class="field" id="textInput">
		    	<%= f.label :conclusion %>
		    	<%= f.text_area :conclusion %>
		    </div>

		    <div class="field" id="textInput">
		    	<%= f.label :maturity %>
		    	<%= f.select :rating , ['Too young', 'Can drink now, will improve' , 'Drink now' , 'Too old'] %>
		    </div>

		    <div class="field" id="textInput">
		    	<%= f.label :rating %>
		    	<%= f.select :rating , ['1', '2' , '3' , '4' , '5' , '6' , '7' , '8' , '9' , '10'] %>
		    </div>

		    <div class="actions">
		      <%= f.submit "Add note", :class => 'submitButton'%>
		    </div>
	    </div>

	<%= token_tag %>

<% end %>

</div>
</div>
</div>

Project_2/app/views/partials/_new_wine_form.html.erb
<h5>Add wine</h5>

<table>
	<div class="large-3 medium-12 small-12 columns">
		<%= form_for(@wine) do |f| %>

	    <div class="field">
	    	<%= f.label :style %>
	    	<%= f.select :style , ['Sparkling', 'White' , 'Rosé' , 'Red' , 'Sweet'] %>
	    </div>

	    <div class="field">
	    	<%= f.label :producer %>
	    	<%= f.text_field :producer %>
	    </div>

	    <div class="field">
	    	<%= f.label :name %>
	    	<%= f.text_field :name %>
	    </div>

	    <div class="field">
	    	<%= f.label :vintage %>
	    	<%= f.text_field :vintage %>
	    </div>

	    <div class="field">
	    	<%= f.label :region %>
	    	<%= f.text_field :region %>
	    </div>

	    <div class="field">
	    	<%= f.label :country %>
	    	<%= f.text_field :country %>
	    </div>

	    <div class="field">
	    	<%= f.label :grape %>
	    	<%= f.text_field :grape %>
	    </div>


	    <div class="field">
	    	<%= f.label :alcohol %>
	    	<%= f.text_field :alcohol %>
	    </div>

	    <div class="field">
	    	<%= f.label :window_start , "Drinking start date" %>
	    	<%= f.text_field :window_start %>
	    </div>

	    <div class="field">
	    	<%= f.label :window_end , "Drinking end date" %>
	    	<%= f.text_field :window_end %>
	    </div>

	    <div class="field">
	    	<%= label_tag 'vendor' %>
	    	<%= text_field_tag 'vendor' %>
	    </div>

	    <div class="field">
	    	<%= label_tag 'price (£)' %>
	    	<%= text_field_tag 'price' %>
	    </div>

	    <div class="field">
	    	<%= label_tag 'quantity' %>
	    	<%= text_field_tag 'bottle[quantity]' %>
	    </div>

	    <div class="actions">
	      <%= f.submit "Add wine" %>
	    </div>

			<%= token_tag %>

		<% end %>
	</div>
</table>	

Project_2/app/views/partials/_show_note.html.erb
<% rating = @note.rating %>	

<div class="row">	
	<div class="large-12 medium-12 small-12 columns">
		<table>
			<tr>
				<td class="noteCategory"><strong>Appearance</td></strong><td class="noteCopy"><%= @note.appearance %></td>
			</tr>
			<tr>
				<td class="noteCategory"><strong>Nose</td></strong><td class="noteCopy"><%= @note.nose %></td>
			</tr>
			<tr>
				<td class="noteCategory"><strong>Palate</td></strong><td class="noteCopy"><%= @note.palate %></td>
			</tr>
			<tr>
				<td class="noteCategory"><strong>Conclusion</td></strong><td class="noteCopy"><%= @note.conclusion %></td>
			</tr>
			<tr>
				<td class="noteCategory"><strong>Maturity</td></strong><td class="noteCopy"><%= @note.maturity %></td>
			</tr>
			<tr>
				<td class="noteCategory"><strong>Rating</td></strong><td class="noteCopy"><% (1..rating).each do |i| %>
						<i class="fa fa-star-o"></i>
					<% end %>
			</tr>			
		</table>
	</div>
</div>

Project_2/app/views/partials/_show_notes.html.erb
<div class="row">
	<div class="small-12 columns">
		<table>
			<thead>
			    <tr>
				    <th>Date</th>
				    <th>User</th>
			      	<th>Name</th>
			      	<th>Note</th>
			      	<th>Rating</th>
			    </tr>
			</thead>
			<tbody>
				<% @notes.each do |note| %>
				<% full_name = "#{note.bottle.wine.producer} #{note.bottle.wine.name} #{note.bottle.wine.vintage}"	%>
				<% rating = note.rating %>						
					<tr>
						<td><%= localize(note.created_at, :format => :uk) %></td>
						<td><%= note.bottle.user.name %></td>
						<td><%= full_name %></td>
	
						<% if controller_name == "user_notes" || controller_name == "user_wines" %>
							<td><%= link_to truncate(note.conclusion, :length => 50), user_note_path(note) %></td>
						<% elsif controller_name == "notes" || controller_name == "wines" %>
							<td><%= link_to truncate(note.conclusion, :length => 50), note %></td>
						<% end %>

						<td class="rating">
						
							<% (1..rating).each do |i| %>
							  <i class="fa fa-star-o"></i>
							<% end %>
						
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

Project_2/app/views/partials/_show_user_of_wine.html.erb
<div class="wineUsers">
	<h6>Users</h6>
	<% @users.each do |user| %>
		<tr><%= link_to user.name.titleize, users_path(user) %></tr><br/>
	<% end %>
</div>

Project_2/app/views/partials/_show_wine.html.erb
<% if @wine.style == "sparkling" %>

	<% bottle_url = "/assets/champagne.jpg" %>

<% elsif @wine.style == "red" %>

	<% bottle_url = "/assets/red.jpg" %>
	
<% elsif @wine.style == "white" %>

	<% bottle_url = "/assets/white.jpg" %>

<% elsif @wine.style == "rose" %>

	<% bottle_url = "/assets/rose.jpg" %>

<% elsif @wine.style == "sweet" %>

	<% bottle_url = "/assets/sweet.jpg" %>				

<% end %>

<div class="small-3 columns">
	<%= image_tag(bottle_url, :class => "showImage") %>
</div>
<div class="small-6 columns">
	<div class="wineDetails">
		<h3 class="wineName"><%= @wine.producer %></h3>
		<h3 class="wineName"><%= "#{@wine.name} #{@wine.vintage}" %></h3>
		<p class = "wineSpec"><a><%= @wine.style %></a>
			
			 |
		
		<a><%= @wine.alcohol %>%</a>
			
			 |
	
		<a><%= @wine.region %></a>
			
			 |
	
		<a><%= @wine.country %></a>
		
		|
		
		<a><%= @wine.grape %></a>
			
			 |
	
		<a><%= "#{@wine.window_start}–#{@wine.window_end}" %></a>
		</p>
	</div>
</div>

Project_2/app/views/partials/_unmarked_subnav.html.erb
<dl class="sub-nav">
  <dd><a href="/user_wines">Your wines</a></dd>
  <dd><a href="/user_notes">Your notes</a></dd>
</dl>

Project_2/app/views/partials/_user_notes_subnav.html.erb
<dl class="sub-nav">
  <dd><a href="/user_wines">Your wines</a></dd>
  <dd class="active"><a href="/user_notes">Your notes</a></dd>
</dl>

Project_2/app/views/partials/_user_wines_subnav.html.erb
<dl class="sub-nav">
  <dd class="active"><a href="/user_wines">Your wines</a></dd>
  <dd><a href="/user_notes">Your notes</a></dd>
</dl>

Project_2/app/views/partials/_users_index.html.erb
<div class="row">
	<div class="small-12 columns">
		<table>
			<thead>
			    <tr>
				    <th>Name</th>
				    <th>Wines</th>
			      	<th>Notes</th>
			    </tr>
			</thead>
			<tbody>
			<% @users.each do |user| %>	
				<tr>
					<td><%= link_to user.name.titleize, user_path(user) %></td>
					<td><%= user.wines.count %></td>
					<td><%= user.notes.count %></td>
				</tr>
			<% end %>		
			</tbody>
		</table>
	</div>
</div>

Project_2/app/views/user_notes/index.html.erb
<div class="row" id="mainBackground">
  <div class="small-10 small-offset-1 columns">
  	<h5 class="head">Your notes</h5>   
    <%= render "/partials/show_notes" %>
  </div>
</div>

Project_2/app/views/user_notes/show.html.erb
<div class="row" id="mainBackground">
  <div class="small-10 small-offset-1 columns"> 
  	<div class="mainDisplay"> 
			<div class="row" id="userWineMain">
		  	<div class="small-12 columns">
		  		<div class="backLink">
						<i class="fa fa-long-arrow-left"></i>	
						<%= link_to 'back to notes', user_notes_path %>
					</div>
					<%= render "/partials/show_wine" %>
					<div class="small-3 columns">				
					</div>
				</div>
			</div>		
		</div>
	</div>
</div>

<div class="row" id="notesArea">
  <div class="small-10 small-offset-1 columns">
		<%= render "/partials/show_note" %>
	</div>
</div>

Project_2/app/views/user_wines/index.html.erb
<div class="row" id="mainBackground">
  <div class="small-10 small-offset-1 columns">
  	<h5 class="head">Your wines</h5>   
    <%= render "/partials/all_wines" %>
  </div>
</div>

Project_2/app/views/user_wines/show.html.erb
<!-- this links to specific js file --> 
<% javascript_include_tag "/javascripts/user_wines_show/user_wines.js" %>
<div class="row" id="mainBackground">
  	<div class="small-10 small-offset-1 columns"> 
  		<div class="mainDisplay"> 
			<div class="row" id="userWineMain">
				<div class="small-12 columns">
					<div class="backLink">
						<i class="fa fa-long-arrow-left"></i>	
						<%= link_to 'back to wines', user_wines_path %>
					</div>

					<div class="row">

						<%= render "/partials/show_wine" %>

						<div class="small-3 columns" id="addNoteToDrink">
							<h5 id="toDrink">In cellar: <%= @quantity %></h5>
							<% if @quantity > 0 %>
								<button id='addNoteButton'>Add note</button>
							<% end %>				
						</div>
					</div>	
			  	</div>
			</div>  
		</div>
	</div>	
</div>

<div class="row" id="notesArea">
  	<div class="small-10 small-offset-1 columns">
			<div id="newNoteForm">
				<%= render "/partials/new_note_form" %>
			</div>
		<%= render "/partials/show_notes" %>
	</div>
</div>

Project_2/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

Project_2/app/views/users/index.html.erb
<div class="row" id="mainBackground">
  <div class="small-10 small-offset-1 columns">
  	<h5 class="head">CellarBook users</h5>   
    <%= render "/partials/users_index" %>
  </div>
</div>

Project_2/app/views/users/show.html.erb
<div class="row" id="mainBackground">
  <div class="small-10 small-offset-1 columns">
  	<h5 class="head">User profile</h5>    
    <div class="row">	
    	<div class="large-12 medium-12 small-12 columns">
    		<table>
    			<tr>
    				<td class="profileCategory"><strong>Name</td></strong><td class="userDetails"><%= @user.name %></td>
    			</tr>
    			<tr>
    				<td class="profileCategory"><strong>Email</td></strong><td class="userDetails"><%= @user.email %></td>
    			</tr>
    			<tr>
    				<td class="profileCategory"><strong>Password</td></strong><td class="userDetails"><%= @user.password_digest %></td>
    			</tr>			
    		</table>
    		<%= link_to 'Edit profile' , edit_user_path %>
    	</div>
    </div>
  </div>
</div>

Project_2/app/views/wines/show.html.erb
<div class="row" id="mainBackground">
  <div class="small-10 small-offset-1 columns"> 
  	<div class="mainDisplay"> 
			<div class="row" id="userWineMain">
		  	<div class="small-12 columns">
		  		<div class="backLink">
						<i class="fa fa-long-arrow-left"></i>	
						<%= link_to 'back to wines', wines_path %>
					</div>
					<%= render "/partials/show_wine" %>
					<div class="small-3 columns">				
					</div>
				</div>
			</div>		
		</div>
	</div>
</div>

<div class="row" id="notesArea">
  <div class="small-10 small-offset-1 columns">
		<%= render "/partials/show_notes" %>
	</div>
</div>